# Generated by Django 3.1.3 on 2020-12-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closingDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
