version: "3.8"
   
services:
  db:
    image: postgres:13.1-alpine
    env_file:
      - ./docker/prod/.db.env
  app:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    depends_on:
      - db
    expose:
      - "8000"
    env_file:
      - ./docker/prod/.env
    environment:
      DATABASE_HOST: db
    volumes:
      - staticfiles:/staticfiles
    command: sh -c '/wait-for db:5432 -- gunicorn app.wsgi -b 0.0.0.0:8000'
  nginx:
    build: ./docker/prod/nginx/
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - staticfiles:/staticfiles

volumes:
  staticfiles: