version: "3.8"
   
services:
  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=h8sahd1908998b8789h1
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: czbwg1#bq#@t)vw#0l1q+7d1_+u6a55a%brs*e#@7bebu6gb@z
      DATABASE_DB: postgres_db
      DATABASE_USER: postgres_user
      DATABASE_PASSWORD: h8sahd1908998b8789h1
      DATABASE_HOST: db
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000

