version: "3.8"
   
services:
  db:
    image: postgres:13.1-alpine
    env_file:
      - ./docker/prod/.db.env
    volumes:
      - ./data/prod:/var/lib/postgresql/data/
  app:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    depends_on:
      - db
    expose:
      - "8000"
    env_file:
      - ./docker/prod/.env
    environment:
      DATABASE_HOST: db
    volumes:
      - staticfiles:/files/staticfiles
    command: sh -c '/files/wait-for db:5432 -- sh /files/entrypoint.sh'
  nginx:
    build: ./docker/prod/nginx/
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - staticfiles:/staticfiles

volumes:
  staticfiles:
