version: "3.8"
   
services:
  db:
    image: postgres:13.1-alpine
    env_file:
      - ./docker/dev/.db.env
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./docker/dev/.env
    environment:
      DATABASE_HOST: db
    volumes:
      - ./app:/app
    command: sh -c '/wait-for db:5432 -- python manage.py migrate && 
                                         python manage.py runserver 0.0.0.0:8000'

